name: API Access

on:
  push:
    branches: [ main ]

jobs:
  access_api:
    runs-on: ubuntu-latest
    steps:
    - name: Run Python script
      run: python content_writing.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
